[package]
name = "bloxide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
find_folder = "0.3.0"
gfx_device_gl = "0.16.2"
rand = "0.8.4"